Repository anfema/website, pull requests merged in 2020-11, with the labels that each got.

#394 Enhancement: Update style of project header
  app/styles/_config/_mixins/_customers.scss
  app/styles/components/_project-header.scss
  app/ui/components/project-header/template.hbs
  contents/de/projects/5.mystaffpilot.yaml
Labels: Enhancement

#395 Bug: Fix mailto-link in page-footer component
  app/styles/components/_contact.scss
  app/ui/components/contact/component.js
  app/ui/components/contact/template.hbs
  app/ui/components/page-footer/template.hbs
  contents/de/projects/5.mystaffpilot.yaml
Labels: Bug

#397 Enhancement: Fix styling of content-quote
  app/styles/components/_content-quote.scss
Labels: Enhancement

#389 update ember-cli version
  .editorconfig
  .eslintrc.js
  .gitignore
  .template-lintrc.js
  .travis.yml
  app/app.js
  app/resolver.js
  app/router.js
  app/styles/_global.scss
  app/ui/application/route.js
  app/ui/components/anfema-logo/logo/index.js
  app/ui/components/content-slider/component.js
  app/ui/components/language-select/component.js
  app/ui/components/services-menu-link/component.js
  app/ui/imprint/route.js
  app/ui/language/index/controller.js
  app/ui/language/index/route.js
  app/ui/language/route.js
  app/ui/projects/detail/controller.js
  app/ui/projects/detail/route.js
  app/ui/projects/index/route.js
  codemods.log
  config/ember-cli-update.json
  config/ember-intl.js
  config/environment.js
  config/optional-features.json
  config/targets.js
  ember-cli-build.js
  package.json
  testem.js
  tests/integration/ui/components/contact/component-test.js
  tests/integration/ui/components/content-quote/component-test.js
  tests/integration/ui/components/project-features-item/component-test.js
  tests/integration/ui/components/project-features/component-test.js
  tests/integration/ui/components/project-icons/component-test.js
  tests/test-helper.js
  yarn.lock
Labels: Chore, Priority: !!!

#413 downgrade eslint until anfema-ruleset is updated
  .eslintrc.js
  package.json
  yarn.lock
Labels: Chore, Enhancement, Priority: !!!

#404 Bug: Check project for missing translations
  contents/en/projects/5.mystaffpilot.yaml
Labels: Bug, Change Request

#415 fix lint-errors due to ember updates
  app/app.js
  app/router.js
  app/ui/components/contact/component.js
  app/ui/language/index/controller.js
  config/environment.js
  tests/integration/ui/components/contact/component-test.js
  yarn.lock
Labels: Chore, Enhancement, Priority: !!!

#403 Enhancement: Refactor styling of body instead of using .ember-view class
  app/styles/_global.scss
Labels: Bug, Chore, Enhancement

#411 Enhancement: Update Knauf lookbook project-detail page
  app/styles/_config/_mixins/_customers.scss
  contents/de/projects/2.knauf.yaml
  contents/en/projects/2.knauf.yaml
Labels: Enhancement

#416 Enhancement: Update IDnow project-detail page
  app/styles/_config/_mixins/_customers.scss
  contents/de/projects/3.idnow.yaml
  contents/en/projects/3.idnow.yaml
Labels: Enhancement

#417 Enhancement: Update Tod's project-detail page
  app/styles/_config/_mixins/_customers.scss
  contents/de/projects/6.tods.yaml
  contents/en/projects/6.tods.yaml
Labels: Enhancement

#418 Enhancement: Update Pingonaut project-detail page
  app/styles/_config/_mixins/_customers.scss
  app/ui/components/project-icons/template.hbs
  contents/de/projects/7.pingonaut.yaml
  contents/en/projects/7.pingonaut.yaml
Labels: Enhancement

#419 Enhancement: Update Ferchau project-detail page
  app/styles/_config/_mixins/_customers.scss
  contents/de/projects/8.ferchau.yaml
  contents/en/projects/8.ferchau.yaml
Labels: Enhancement

#420 Enhancement: Create Paulaner project-detail page
  app/styles/_config/_mixins/_customers.scss
  app/styles/components/_project-features.scss
  app/styles/components/_project-icons.scss
  app/ui/components/project-features/template.hbs
  app/ui/components/project-icons/template.hbs
  contents/de/projects/10.paulaner.yaml
  contents/en/projects/10.paulaner.yaml
Labels: Enhancement

#421 Enhancement: Create Audi project-detail page
  app/styles/_config/_mixins/_customers.scss
  app/styles/components/_project-icons.scss
  contents/de/projects/9.audi.yaml
  contents/en/projects/9.audi.yaml
Labels: Enhancement

#426 Enhancement: Add english translation for Audi
  app/styles/components/_project-header.scss
  app/styles/components/_project-icons.scss
  app/ui/components/project-icons/template.hbs
  contents/de/projects/10.paulaner.yaml
  contents/de/projects/5.mystaffpilot.yaml
  contents/de/projects/9.audi.yaml
  contents/en/projects/10.paulaner.yaml
  contents/en/projects/5.mystaffpilot.yaml
  contents/en/projects/9.audi.yaml
Labels: Enhancement

#427 Enhancement: Add english translation for Paulaner
  contents/en/projects/10.paulaner.yaml
Labels: Enhancement

#428 Enhancement: Fix text styling of landingpage
  app/styles/components/_content-lp-cover.scss
  app/styles/components/_content-lp-text.scss
  app/styles/components/_services-slide.scss
Labels: Enhancement
