Repository anfema/website, pull requests merged in 2021-03, with the labels that each got.

#475 Enhancement: Smaller design and text issues
  app/styles/_config/_mixins/_customers.scss
  app/styles/components/_content-lp-cover.scss
  app/styles/components/_project-header.scss
  app/styles/components/_project-technology.scss
  app/styles/components/_projects-list.scss
  app/ui/components/page-footer/component.js
  app/ui/components/page-footer/template.hbs
  app/ui/components/projects-list/component.js
  app/ui/components/projects-list/template.hbs
  contents/de/projects/11.bcg.yaml
  contents/de/projects/12.knaufAroom.yaml
  contents/de/projects/2.knaufLookbook.yaml
  contents/en/projects/1.bmw.yaml
  contents/en/projects/10.paulaner.yaml
  contents/en/projects/11.bcg.yaml
  contents/en/projects/12.knaufAroom.yaml
  contents/en/projects/2.knaufLookbook.yaml
  contents/en/projects/3.idnow.yaml
  contents/en/projects/5.mystaffpilot.yaml
  contents/en/projects/6.tods.yaml
  contents/en/projects/7.pingonaut.yaml
  contents/en/projects/8.ferchau.yaml
  contents/en/projects/9.audi-disabled.yaml
  translations/de.yaml
  translations/en.yaml
Labels: Enhancement

#485 add missing translations to test Integration | Component | projects-list
  config/ember-intl.js
  tests/integration/ui/components/projects-list/component-test.js
  translations/en.yaml
Labels: Enhancement, Priority: !!!

#487 update travis config and remove deploy-code
  .travis.yml
  .travis/deploy-dev.sh
  .travis/deploy-live.sh
Labels: Chore, Priority: !!!

#489 update privacy policy and imprint texts
  app/ui/components/page-footer/template.hbs
  contents/de/imprint.yaml
  contents/en/imprint.yaml
Labels: Chore, Priority: !!!

#491 update translations
  contents/de/index.yaml
  contents/de/projects/1.bmw.yaml
  contents/de/projects/10.paulaner.yaml
  contents/de/projects/12.knaufAroom.yaml
  contents/de/projects/2.knaufLookbook.yaml
  contents/de/projects/3.idnow.yaml
  contents/de/projects/5.mystaffpilot.yaml
  contents/de/projects/6.tods.yaml
  contents/de/projects/7.pingonaut.yaml
  contents/de/projects/8.ferchau.yaml
  contents/en/index.yaml
  contents/en/projects/1.bmw.yaml
  contents/en/projects/10.paulaner.yaml
  contents/en/projects/12.knaufAroom.yaml
  contents/en/projects/2.knaufLookbook.yaml
  contents/en/projects/3.idnow.yaml
  contents/en/projects/5.mystaffpilot.yaml
  contents/en/projects/6.tods.yaml
  contents/en/projects/7.pingonaut.yaml
  contents/en/projects/8.ferchau.yaml
  translations/de.yaml
Labels: Enhancement

#493 Enhancement: Change assets in overview
  contents/de/projects/11.bcg-disabled.yaml
  contents/de/projects/12.knaufAroom.yaml
  contents/de/projects/2.knaufLookbook.yaml
  contents/en/projects/11.bcg-disabled.yaml
  contents/en/projects/12.knaufAroom.yaml
  contents/en/projects/2.knaufLookbook.yaml
Labels: Enhancement

#499 Enable Audi Project for review
  app/styles/components/_projects-list.scss
  contents/de/projects/9.audi-disabled.yaml
  contents/de/projects/9.audi.yaml
  contents/en/projects/9.audi.yaml
Labels: Enhancement

#497 Enhancement: Update imprint adress
  contents/de/imprint.yaml
  contents/de/projects/5.mystaffpilot.yaml
  contents/en/imprint.yaml
  contents/en/projects/5.mystaffpilot.yaml
  tests/integration/ui/components/projects-list/component-test.js
Labels: Enhancement

#496 Enhancement: Update project overview
  app/styles/components/_projects-list.scss
  contents/de/projects/11.bcg-disabled.yaml
  contents/de/projects/3.idnow.yaml
  contents/en/projects/11.bcg-disabled.yaml
  contents/en/projects/3.idnow.yaml
Labels: Enhancement

#500 Enhancement: Update project overview
  app/styles/components/_projects-list.scss
Labels: Enhancement
